### ISSUE TITLE
Account confirmation points to `localhost:3000`

### ISSUE THREAD

**Issue by joshistoast** [madebyfabian/zingio#1]
When signing up for a new account a confirmation email is sent to your email. The link that's sent in the email points to localhost:3000.
I assume this is supabase-related.

**Comment by madebyfabian** [comment]
@joshwcorbett Hey there, great that you've tried out the product. Yes that is indeed supabase related, will fix that! :)

**Comment by madebyfabian** [comment]
@joshwcorbett Try by signing up again, you now should get the right email link 😊

**Comment by joshistoast** [comment]
Now working
